name: Production:Deploy CI / CD

on: 
 push:
   branches: [main]

permissions:
  contents: read

jobs:
  build-test-deploy-prod:
    runs-on: defi-dex-linux-medium
    
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Setup Node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: '18'

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y make gcc g++ # Install make and other build tools

    - name: Set up Yarn
      run: npm install -g yarn
      
    - name: Install Dependencies
      run: yarn
      
    - name: Check Format
      run: yarn format
      
    - name: Lint
      run: yarn lint

    - name: Build App
      run: | 
        yarn build
      
